/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Permissions } from "./Permissions";
export type { Roles } from "./Roles";
export * as factories from "./factories";
export { Permissions__factory } from "./factories/Permissions__factory";
export { Roles__factory } from "./factories/Roles__factory";
