/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Permissions__factory } from "./Permissions__factory";
export { Roles__factory } from "./Roles__factory";
