/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface RolesInterface extends utils.Interface {
  functions: {
    "allowTarget(uint16,address,uint8)": FunctionFragment;
    "assignRoles(address,uint16[],bool[])": FunctionFragment;
    "avatar()": FunctionFragment;
    "defaultRoles(address)": FunctionFragment;
    "disableModule(address,address)": FunctionFragment;
    "enableModule(address)": FunctionFragment;
    "execTransactionFromModule(address,uint256,bytes,uint8)": FunctionFragment;
    "execTransactionFromModuleReturnData(address,uint256,bytes,uint8)": FunctionFragment;
    "execTransactionWithRole(address,uint256,bytes,uint8,uint16,bool)": FunctionFragment;
    "execTransactionWithRoleReturnData(address,uint256,bytes,uint8,uint16,bool)": FunctionFragment;
    "getGuard()": FunctionFragment;
    "getModulesPaginated(address,uint256)": FunctionFragment;
    "guard()": FunctionFragment;
    "isModuleEnabled(address)": FunctionFragment;
    "multisend()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeTarget(uint16,address)": FunctionFragment;
    "scopeAllowFunction(uint16,address,bytes4,uint8)": FunctionFragment;
    "scopeFunction(uint16,address,bytes4,bool[],uint8[],uint8[],bytes[],uint8)": FunctionFragment;
    "scopeFunctionExecutionOptions(uint16,address,bytes4,uint8)": FunctionFragment;
    "scopeParameter(uint16,address,bytes4,uint256,uint8,uint8,bytes)": FunctionFragment;
    "scopeParameterAsOneOf(uint16,address,bytes4,uint256,uint8,bytes[])": FunctionFragment;
    "scopeRevokeFunction(uint16,address,bytes4)": FunctionFragment;
    "scopeTarget(uint16,address)": FunctionFragment;
    "setAvatar(address)": FunctionFragment;
    "setDefaultRole(address,uint16)": FunctionFragment;
    "setGuard(address)": FunctionFragment;
    "setMultisend(address)": FunctionFragment;
    "setTarget(address)": FunctionFragment;
    "setUp(bytes)": FunctionFragment;
    "target()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unscopeParameter(uint16,address,bytes4,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allowTarget"
      | "assignRoles"
      | "avatar"
      | "defaultRoles"
      | "disableModule"
      | "enableModule"
      | "execTransactionFromModule"
      | "execTransactionFromModuleReturnData"
      | "execTransactionWithRole"
      | "execTransactionWithRoleReturnData"
      | "getGuard"
      | "getModulesPaginated"
      | "guard"
      | "isModuleEnabled"
      | "multisend"
      | "owner"
      | "renounceOwnership"
      | "revokeTarget"
      | "scopeAllowFunction"
      | "scopeFunction"
      | "scopeFunctionExecutionOptions"
      | "scopeParameter"
      | "scopeParameterAsOneOf"
      | "scopeRevokeFunction"
      | "scopeTarget"
      | "setAvatar"
      | "setDefaultRole"
      | "setGuard"
      | "setMultisend"
      | "setTarget"
      | "setUp"
      | "target"
      | "transferOwnership"
      | "unscopeParameter"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowTarget",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRoles",
    values: [string, BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(functionFragment: "avatar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultRoles",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "disableModule",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "enableModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionFromModule",
    values: [string, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionFromModuleReturnData",
    values: [string, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionWithRole",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "execTransactionWithRoleReturnData",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(functionFragment: "getGuard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getModulesPaginated",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "guard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isModuleEnabled",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "multisend", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTarget",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeAllowFunction",
    values: [BigNumberish, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeFunction",
    values: [
      BigNumberish,
      string,
      BytesLike,
      boolean[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeFunctionExecutionOptions",
    values: [BigNumberish, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeParameter",
    values: [
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeParameterAsOneOf",
    values: [
      BigNumberish,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeRevokeFunction",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "scopeTarget",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "setAvatar", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setDefaultRole",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setGuard", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMultisend",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setTarget", values: [string]): string;
  encodeFunctionData(functionFragment: "setUp", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "unscopeParameter",
    values: [BigNumberish, string, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "avatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionFromModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionFromModuleReturnData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionWithRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execTransactionWithRoleReturnData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getModulesPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isModuleEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multisend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeAllowFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeFunctionExecutionOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeParameter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeParameterAsOneOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeRevokeFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scopeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAvatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMultisend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unscopeParameter",
    data: BytesLike
  ): Result;

  events: {
    "AssignRoles(address,uint16[],bool[])": EventFragment;
    "AvatarSet(address,address)": EventFragment;
    "ChangedGuard(address)": EventFragment;
    "DisabledModule(address)": EventFragment;
    "EnabledModule(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RolesModSetup(address,address,address,address)": EventFragment;
    "SetDefaultRole(address,uint16)": EventFragment;
    "SetMultisendAddress(address)": EventFragment;
    "TargetSet(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssignRoles"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AvatarSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangedGuard"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisabledModule"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnabledModule"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RolesModSetup"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDefaultRole"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMultisendAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TargetSet"): EventFragment;
}

export interface AssignRolesEventObject {
  module: string;
  roles: number[];
  memberOf: boolean[];
}
export type AssignRolesEvent = TypedEvent<
  [string, number[], boolean[]],
  AssignRolesEventObject
>;

export type AssignRolesEventFilter = TypedEventFilter<AssignRolesEvent>;

export interface AvatarSetEventObject {
  previousAvatar: string;
  newAvatar: string;
}
export type AvatarSetEvent = TypedEvent<[string, string], AvatarSetEventObject>;

export type AvatarSetEventFilter = TypedEventFilter<AvatarSetEvent>;

export interface ChangedGuardEventObject {
  guard: string;
}
export type ChangedGuardEvent = TypedEvent<[string], ChangedGuardEventObject>;

export type ChangedGuardEventFilter = TypedEventFilter<ChangedGuardEvent>;

export interface DisabledModuleEventObject {
  module: string;
}
export type DisabledModuleEvent = TypedEvent<
  [string],
  DisabledModuleEventObject
>;

export type DisabledModuleEventFilter = TypedEventFilter<DisabledModuleEvent>;

export interface EnabledModuleEventObject {
  module: string;
}
export type EnabledModuleEvent = TypedEvent<[string], EnabledModuleEventObject>;

export type EnabledModuleEventFilter = TypedEventFilter<EnabledModuleEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RolesModSetupEventObject {
  initiator: string;
  owner: string;
  avatar: string;
  target: string;
}
export type RolesModSetupEvent = TypedEvent<
  [string, string, string, string],
  RolesModSetupEventObject
>;

export type RolesModSetupEventFilter = TypedEventFilter<RolesModSetupEvent>;

export interface SetDefaultRoleEventObject {
  module: string;
  defaultRole: number;
}
export type SetDefaultRoleEvent = TypedEvent<
  [string, number],
  SetDefaultRoleEventObject
>;

export type SetDefaultRoleEventFilter = TypedEventFilter<SetDefaultRoleEvent>;

export interface SetMultisendAddressEventObject {
  multisendAddress: string;
}
export type SetMultisendAddressEvent = TypedEvent<
  [string],
  SetMultisendAddressEventObject
>;

export type SetMultisendAddressEventFilter =
  TypedEventFilter<SetMultisendAddressEvent>;

export interface TargetSetEventObject {
  previousTarget: string;
  newTarget: string;
}
export type TargetSetEvent = TypedEvent<[string, string], TargetSetEventObject>;

export type TargetSetEventFilter = TypedEventFilter<TargetSetEvent>;

export interface Roles extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RolesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allowTarget(
      role: BigNumberish,
      targetAddress: string,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    assignRoles(
      module: string,
      _roles: BigNumberish[],
      memberOf: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    avatar(overrides?: CallOverrides): Promise<[string]>;

    defaultRoles(arg0: string, overrides?: CallOverrides): Promise<[number]>;

    disableModule(
      prevModule: string,
      module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enableModule(
      module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execTransactionFromModule(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execTransactionFromModuleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execTransactionWithRole(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execTransactionWithRoleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getGuard(overrides?: CallOverrides): Promise<[string] & { _guard: string }>;

    getModulesPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[], string] & { array: string[]; next: string }>;

    guard(overrides?: CallOverrides): Promise<[string]>;

    isModuleEnabled(
      _module: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    multisend(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeAllowFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      isParamScoped: boolean[],
      paramType: BigNumberish[],
      paramComp: BigNumberish[],
      compValue: BytesLike[],
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeFunctionExecutionOptions(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      paramComp: BigNumberish,
      compValue: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeParameterAsOneOf(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      compValues: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeRevokeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scopeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAvatar(
      _avatar: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDefaultRole(
      module: string,
      role: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGuard(
      _guard: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMultisend(
      _multisend: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTarget(
      _target: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUp(
      initParams: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    target(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unscopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allowTarget(
    role: BigNumberish,
    targetAddress: string,
    options: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  assignRoles(
    module: string,
    _roles: BigNumberish[],
    memberOf: boolean[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  avatar(overrides?: CallOverrides): Promise<string>;

  defaultRoles(arg0: string, overrides?: CallOverrides): Promise<number>;

  disableModule(
    prevModule: string,
    module: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enableModule(
    module: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execTransactionFromModule(
    to: string,
    value: BigNumberish,
    data: BytesLike,
    operation: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execTransactionFromModuleReturnData(
    to: string,
    value: BigNumberish,
    data: BytesLike,
    operation: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execTransactionWithRole(
    to: string,
    value: BigNumberish,
    data: BytesLike,
    operation: BigNumberish,
    role: BigNumberish,
    shouldRevert: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execTransactionWithRoleReturnData(
    to: string,
    value: BigNumberish,
    data: BytesLike,
    operation: BigNumberish,
    role: BigNumberish,
    shouldRevert: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getGuard(overrides?: CallOverrides): Promise<string>;

  getModulesPaginated(
    start: string,
    pageSize: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string[], string] & { array: string[]; next: string }>;

  guard(overrides?: CallOverrides): Promise<string>;

  isModuleEnabled(_module: string, overrides?: CallOverrides): Promise<boolean>;

  multisend(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeTarget(
    role: BigNumberish,
    targetAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeAllowFunction(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    options: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeFunction(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    isParamScoped: boolean[],
    paramType: BigNumberish[],
    paramComp: BigNumberish[],
    compValue: BytesLike[],
    options: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeFunctionExecutionOptions(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    options: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeParameter(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    paramIndex: BigNumberish,
    paramType: BigNumberish,
    paramComp: BigNumberish,
    compValue: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeParameterAsOneOf(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    paramIndex: BigNumberish,
    paramType: BigNumberish,
    compValues: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeRevokeFunction(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scopeTarget(
    role: BigNumberish,
    targetAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAvatar(
    _avatar: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDefaultRole(
    module: string,
    role: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGuard(
    _guard: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMultisend(
    _multisend: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTarget(
    _target: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUp(
    initParams: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  target(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unscopeParameter(
    role: BigNumberish,
    targetAddress: string,
    functionSig: BytesLike,
    paramIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowTarget(
      role: BigNumberish,
      targetAddress: string,
      options: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    assignRoles(
      module: string,
      _roles: BigNumberish[],
      memberOf: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    avatar(overrides?: CallOverrides): Promise<string>;

    defaultRoles(arg0: string, overrides?: CallOverrides): Promise<number>;

    disableModule(
      prevModule: string,
      module: string,
      overrides?: CallOverrides
    ): Promise<void>;

    enableModule(module: string, overrides?: CallOverrides): Promise<void>;

    execTransactionFromModule(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    execTransactionFromModuleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    execTransactionWithRole(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    execTransactionWithRoleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; returnData: string }>;

    getGuard(overrides?: CallOverrides): Promise<string>;

    getModulesPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[], string] & { array: string[]; next: string }>;

    guard(overrides?: CallOverrides): Promise<string>;

    isModuleEnabled(
      _module: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    multisend(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeAllowFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      isParamScoped: boolean[],
      paramType: BigNumberish[],
      paramComp: BigNumberish[],
      compValue: BytesLike[],
      options: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeFunctionExecutionOptions(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      paramComp: BigNumberish,
      compValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeParameterAsOneOf(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      compValues: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    scopeRevokeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    scopeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAvatar(_avatar: string, overrides?: CallOverrides): Promise<void>;

    setDefaultRole(
      module: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setGuard(_guard: string, overrides?: CallOverrides): Promise<void>;

    setMultisend(_multisend: string, overrides?: CallOverrides): Promise<void>;

    setTarget(_target: string, overrides?: CallOverrides): Promise<void>;

    setUp(initParams: BytesLike, overrides?: CallOverrides): Promise<void>;

    target(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unscopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssignRoles(address,uint16[],bool[])"(
      module?: null,
      roles?: null,
      memberOf?: null
    ): AssignRolesEventFilter;
    AssignRoles(
      module?: null,
      roles?: null,
      memberOf?: null
    ): AssignRolesEventFilter;

    "AvatarSet(address,address)"(
      previousAvatar?: string | null,
      newAvatar?: string | null
    ): AvatarSetEventFilter;
    AvatarSet(
      previousAvatar?: string | null,
      newAvatar?: string | null
    ): AvatarSetEventFilter;

    "ChangedGuard(address)"(guard?: null): ChangedGuardEventFilter;
    ChangedGuard(guard?: null): ChangedGuardEventFilter;

    "DisabledModule(address)"(module?: null): DisabledModuleEventFilter;
    DisabledModule(module?: null): DisabledModuleEventFilter;

    "EnabledModule(address)"(module?: null): EnabledModuleEventFilter;
    EnabledModule(module?: null): EnabledModuleEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "RolesModSetup(address,address,address,address)"(
      initiator?: string | null,
      owner?: string | null,
      avatar?: string | null,
      target?: null
    ): RolesModSetupEventFilter;
    RolesModSetup(
      initiator?: string | null,
      owner?: string | null,
      avatar?: string | null,
      target?: null
    ): RolesModSetupEventFilter;

    "SetDefaultRole(address,uint16)"(
      module?: null,
      defaultRole?: null
    ): SetDefaultRoleEventFilter;
    SetDefaultRole(
      module?: null,
      defaultRole?: null
    ): SetDefaultRoleEventFilter;

    "SetMultisendAddress(address)"(
      multisendAddress?: null
    ): SetMultisendAddressEventFilter;
    SetMultisendAddress(
      multisendAddress?: null
    ): SetMultisendAddressEventFilter;

    "TargetSet(address,address)"(
      previousTarget?: string | null,
      newTarget?: string | null
    ): TargetSetEventFilter;
    TargetSet(
      previousTarget?: string | null,
      newTarget?: string | null
    ): TargetSetEventFilter;
  };

  estimateGas: {
    allowTarget(
      role: BigNumberish,
      targetAddress: string,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    assignRoles(
      module: string,
      _roles: BigNumberish[],
      memberOf: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    avatar(overrides?: CallOverrides): Promise<BigNumber>;

    defaultRoles(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    disableModule(
      prevModule: string,
      module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enableModule(
      module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execTransactionFromModule(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execTransactionFromModuleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execTransactionWithRole(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execTransactionWithRoleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getGuard(overrides?: CallOverrides): Promise<BigNumber>;

    getModulesPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    guard(overrides?: CallOverrides): Promise<BigNumber>;

    isModuleEnabled(
      _module: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multisend(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeAllowFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      isParamScoped: boolean[],
      paramType: BigNumberish[],
      paramComp: BigNumberish[],
      compValue: BytesLike[],
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeFunctionExecutionOptions(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      paramComp: BigNumberish,
      compValue: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeParameterAsOneOf(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      compValues: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeRevokeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scopeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAvatar(
      _avatar: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDefaultRole(
      module: string,
      role: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGuard(
      _guard: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMultisend(
      _multisend: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTarget(
      _target: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUp(
      initParams: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    target(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unscopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowTarget(
      role: BigNumberish,
      targetAddress: string,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    assignRoles(
      module: string,
      _roles: BigNumberish[],
      memberOf: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    avatar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultRoles(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    disableModule(
      prevModule: string,
      module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enableModule(
      module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execTransactionFromModule(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execTransactionFromModuleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execTransactionWithRole(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execTransactionWithRoleReturnData(
      to: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      role: BigNumberish,
      shouldRevert: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getGuard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getModulesPaginated(
      start: string,
      pageSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    guard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isModuleEnabled(
      _module: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multisend(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeAllowFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      isParamScoped: boolean[],
      paramType: BigNumberish[],
      paramComp: BigNumberish[],
      compValue: BytesLike[],
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeFunctionExecutionOptions(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      paramComp: BigNumberish,
      compValue: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeParameterAsOneOf(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      paramType: BigNumberish,
      compValues: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeRevokeFunction(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scopeTarget(
      role: BigNumberish,
      targetAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAvatar(
      _avatar: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDefaultRole(
      module: string,
      role: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGuard(
      _guard: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMultisend(
      _multisend: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTarget(
      _target: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUp(
      initParams: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    target(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unscopeParameter(
      role: BigNumberish,
      targetAddress: string,
      functionSig: BytesLike,
      paramIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
